
server:
  port: 8080

spring:
  # 文件上传
  servlet:
    multipart:
      # 单个文件大小
      max-file-size: 100MB
      # 设置总上传的文件大小
      max-request-size: 200MB

# minio存储配置
minio:
  accessKey: adminhkkj    #minio账号
  secretKey: adminhkkj123   #minio密码
  bucket: smart-construction-dev   #minio里面桶的名字，
  endpoint: http://47.96.150.227:9000   #服务器地址
  readPath: http://47.96.150.227:9000
